version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "${REDIS_PATH}/data:/data"
#      - redis_data:/data

  custom-cake:
    image: jjaen0823/custom-cake:latest
    container_name: custom-cake-dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

