FROM openjdk:11
EXPOSE 8080
ARG JAR_FILE=/build/libs/custom-cake-backend-0.0.1-SNAPSHOT.jar
#VOLUME ["/var/log"]
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=dev","/app.jar"]
