name: Develop Branch PR Check

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'custom-cake-backend/**'

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  
jobs:
  pr-requirements-check:
    defaults:
      run:
        shell: bash
        working-directory: custom-cake-backend
        
    runs-on: ubuntu-latest
    steps:
      # setup MySQL
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'customcake'
          mysql user: 'admin'
          mysql password: '1234'

#      - name: Checkout code
#        uses: actions/checkout@v2.3.1

      - name: Branch name check
        if: ${{ !startsWith(env.BRANCH_NAME, 'CAKE-') && !startsWith(env.BRANCH_NAME, 'HOTFIX-') && env.BRANCH_NAME != 'main' && env.BRANCH_NAME != 'develop' }}
        run: exit 1

      - name: Insert Dynmaic Configuration to gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" >> ~/.gradle/gradle.properties

      - name: Gradle clean
        shell: bash
        run: ./gradlew clean
        
      - name: Test case check
        run: ./gradlew test --continue

      - name: Build check (without testcase)
        run: ./gradlew build -x test
