name: Develop Branch PR Check

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'custom-cake-backend/**'

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  
jobs:
  pr-requirements-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Branch name check
        if: ${{ !startsWith(env.BRANCH_NAME, 'CAKE-') && !startsWith(env.BRANCH_NAME, 'HOTFIX-') && env.BRANCH_NAME != 'main' && env.BRANCH_NAME != 'develop' }}
        run: exit 1

      - name: Insert Dynmaic Configuration to gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" >> ~/.gradle/gradle.properties
          
  test_and_build_check:
    needs: pr-requirements-check
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: custom-cake-backend
    steps:
      - name: ls
        shell: bash
        run: ls -al
#       - name: chmod gradlew
#         shell: bash
#         run: sudo chmod +x ./gradlew

      - name: Gradle clean
        shell: bash
        run: ./gradlew clean

      - name: Ktlint check
        run: ./gradlew ktlintCheck --continue

      - name: Test case check
        run: ./gradlew test --continue

      - name: Build check (without testcase)
        run: ./gradlew build -x test
