name: Develop Branch PR Check

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'custom-cake-backend/**'

env:
#   BACKEND_PROJECT_PATH: ''
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  
jobs:
  pr-requirements-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Branch name check
        if: ${{ !startsWith(env.BRANCH_NAME, 'CAKE-') && !startsWith(env.BRANCH_NAME, 'HOTFIX-') && env.BRANCH_NAME != 'main' && env.BRANCH_NAME != 'develop' }}
        run: exit 1

      - name: Insert Dynmaic Configuration to gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" >> ~/.gradle/gradle.properties
          
      - name: chmod gradlew
        run: sudo chmod +x ./custom-cake-backend/gradlew

      - name: Gradle clean
        shell: bash
        run: ./custom-cake-backend/gradlew clean

      - name: Ktlint check
        run: ./custom-cake-backend/gradlew ktlintCheck --continue

      - name: Test case check
        run: ./custom-cake-backend/gradlew test --continue

      - name: Build check (without testcase)
        run: ./custom-cake-backend/gradlew build -x test
